# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 07:36
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20180525_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentinstance',
            name='contents',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='viscomponent',
            name='contents',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='contents',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
