# Generated by Django 2.2.1 on 2019-05-30 08:17

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20180525_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentinstance',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='viscomponent',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
