# Generated by Django 3.2.18 on 2024-05-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_auto_20190531_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentinstance',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a brief description of the resource', max_length=1000),
        ),
        migrations.AlterField(
            model_name='viscomponent',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a brief description of the resource', max_length=1000),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a brief description of the resource', max_length=1000),
        ),
    ]
