# Generated by Django 3.2.25 on 2024-10-16 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20240516_0936'),
        ('analysis', '0008_auto_20240517_1559'),
    ]

    operations = [
    ]
