# Generated by Django 3.2.25 on 2024-09-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20240517_1559'),
        ('analysis', '0008_auto_20240613_1630'),
    ]

    operations = [
    ]
