# Generated by Django 3.2.18 on 2024-10-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20240517_1559'),
        ('analysis', '0008_auto_20240523_1337'),
    ]

    operations = [
    ]
