# Generated by Django 3.2.25 on 2025-01-15 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_merge_0008_auto_20240516_0936_0008_auto_20240517_1559'),
        ('analysis', '0009_merge_0008_auto_20240517_1559_0008_auto_20240523_1337'),
    ]

    operations = [
    ]
