# Generated by Django 2.1.1 on 2018-10-05 05:34

import datamanagement.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import private_storage.fields
import private_storage.storage.files
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique ID for this particular resource', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the name of the resource', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of the resource', max_length=1000)),
                ('accessibility', models.CharField(choices=[('pri', 'Private'), ('int', 'Internal'), ('pub', 'Public')], default='pri', max_length=3)),
                ('file', private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=datamanagement.models.get_encoded_filepath)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shared_groups', models.ManyToManyField(blank=True, related_name='datasource_shared_groups', to='auth.Group')),
                ('shared_users', models.ManyToManyField(blank=True, related_name='datasource_shared_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
