# Generated by Django 2.2.1 on 2019-05-30 08:17

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
