# Generated by Django 3.2.25 on 2026-05-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0004_alter_datasource_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
