# Generated by Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0006_populate_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='num_of_rows',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='num_of_columns',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
